import mailgen from 'mailgen';
import 'dotenv/config';
import { mailConfigs } from '../configs/nodeMailer.config.js';

export const sendGeneratedPassowrdToStudent = async (name, studentfemail, autoGeneratedPassword) => {

    console.log(name, studentfemail, autoGeneratedPassword)

    //import mail configs
    let mailTransporter = mailConfigs();


    let MailGenerator = new mailgen({
        theme: "cerberus",
        product: {
            name: "ProjectEase - Modular Management System",
            link: 'http://localhost:5173/',
            logo: 'https://drive.google.com/file/d/10eK8LAzVgURg5ltLVhC2H88V2c8mG4BT/view?usp=share_link'
        }
    })

    var email = {
        body: {
            name: `${name}`,
            intro: `We hope this email finds you well. We have generated a password for you to access your profile.`,

            action: {
                instructions: `Your temporary password is:<br><h1>${autoGeneratedPassword}</h1>`,
                button: {
                    color: '#00FFFF', // Optional action button color
                    text: 'Get Access to your profile',
                    link: 'http://localhost:5173/'
                }
            },
            outro: 'For security purposes, we recommend that you change your password upon first login. If you have any questions or concerns, please do not hesitate to contact our support team.'
        }
    };

    //convert mailgen body into HTML
    let mail = MailGenerator.generate(email);

    //nodemailer sending credentials
    let details = {
        from: process.env.CLIENT_EMAIL,
        to: `${studentfemail}`,
        subject: `You are registered in to the ProjectEase - Modular Management System`,
        html: mail
    }

    //send mail through nodemailer
    await mailTransporter.sendMail(details).then((data) => {
        return data;
    }).catch((error) => {
        return error;
    })

}
